### ISSUE TITLE
CCM

### ISSUE THREAD

**Issue by pshankinclarke** [SugiharaLab/pyEDM#17]
I am using pyEDM version `pyEDM==1.0.3.2`. The CCM example included in the pyEDM documentation(i.e. https://sugiharalab.github.io/EDM_Documentation/algorithms_high_level/) is : 

```
pyEDM.CCM( dataFrame = sardine_anchovy_sst, E=3, columns="anchovy", target="np_sst",
           libSizes  = "10 70 10", showPlot=True, sample=100);

```

I rewrote the function and explicitly declared all the default parameters : 

```
import pyEDM
import pandas as pd
sardine_anchovy_sst = pyEDM.sampleData['sardine_anchovy_sst']
sardine_anchovy_sst[['anchovy','np_sst']].plot();
print(sardine_anchovy_sst.shape[0])
pyEDM.CCM( dataFrame = sardine_anchovy_sst,
           lib = "",
           pred = "",
           E = 3,
           Tp = 1,
           knn = 3 + 1,
           tau = -1,
           exclusionRadius = 0,
           seed = 0,
           columns = "anchovy",
           target = "np_sst",
           libSizes  = "10 70 10",
           showPlot = True,
           sample = 100);
```

I received the following errors : 

1. TypeError: CCM() got an unexpected keyword argument 'lib'
2. TypeError: CCM() got an unexpected keyword argument 'pred'
3.TypeError: CCM() got an unexpected keyword argument 'exclusionRadius'

When I deleted the arguments  'lib', 'pred', and  'exclusionRadius', that is : 

pyEDM.CCM( dataFrame = sardine_anchovy_sst,
           E = 3,
           Tp = 1,
           knn = 3 + 1,
           tau = -1,
           seed = 0,
           columns = "anchovy",
           target = "np_sst",
           libSizes  = "10 70 10",
           showPlot = True,
           sample = 100);

I received the following error :     

```
ComputeError(): obs has 1 nan, pred has 9 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 9 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 10 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 2 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 4 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 7 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 6 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 3 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 5 nan.  ComputeError result invalid.
ComputeError(): obs has 1 nan, pred has 8 nan.  ComputeError result invalid.
Traceback (most recent call last):
  File "ccm.py", line 16, in <module>
    sample = 100);
  File "/home/psc/env/lib/python3.6/site-packages/pyEDM/CoreEDM.py", line 317, in CCM
    verbose )
MemoryError: std::bad_alloc
```

However when I deleted the explicit tau argument the program no longer threw any errors but the graph produced looks very different from the graph provided in the example :

![Figure_2](https://user-images.githubusercontent.com/38367844/108805926-234f4680-7555-11eb-802b-49f21c59ab35.png)

Finally if I deleted the rest of explicit arguments not included in the example : 

```
 pyEDM.CCM( dataFrame = sardine_anchovy_sst,
           E = 3,
           #Tp = 1,
           #knn = 3 + 1,
           #tau = -1,
           #seed = 0,
           columns = "anchovy",
           target = "np_sst",
           libSizes  = "10 70 10",
           showPlot = True,
           sample = 100);
```
My graph looks identical to the graph in the example provided :

![Figure_3](https://user-images.githubusercontent.com/38367844/108806051-85a84700-7555-11eb-9a83-dedb00487592.png)

Could you clarify : 

1. Are 'lib', 'pred', and  'exclusionRadius' still parameters for the ccm function as stated in the documentation? 
2. Why does explicitly stating the the default arguments  change the result in the example problem?

Thank you!

**Comment by SoftwareLiteracy** [comment]
Thanks for the checks.

Please note that version 1.0.3.2 is not supported, and, has known bugs.  Please upgrade to 1.7.5.
```
>>> from pyEDM import *
>>> pyEDM.__version__
'1.7.5.0'
```

CCM arguments are:
```
>>> import inspect
>>> inspect.signature( CCM )
<Signature (pathIn='./', dataFile='', dataFrame=None, pathOut='./', predictFile='', 
E=0, Tp=0, knn=0, tau=-1, exclusionRadius=0, columns='', target='', libSizes='', 
sample=0, random=True, replacement=False, seed=0, includeData=False, 
verbose=False, showPlot=False)>
```
`lib` and `pred` are not used.  This is becuse the library sizes are specified in `libSizes`, and the full record `pred` is used to evaluate each model. 

Here's an example with exclusionRadius:
```
CCM( dataFrame = sampleData['block_3sp'], E = 3, columns = "x_t", target = "z_t", 
     libSizes  = "50 190 10", sample = 100, exclusionRadius = 2 )
    LibSize   x_t:z_t   z_t:x_t
0      50.0  0.806143  0.589280
1      60.0  0.810024  0.593846
2      70.0  0.810642  0.600271
3      80.0  0.813031  0.610370
4      90.0  0.815093  0.621687
5     100.0  0.815645  0.622583
6     110.0  0.814984  0.629480
7     120.0  0.816575  0.632445
8     130.0  0.817393  0.636732
9     140.0  0.817429  0.638641
10    150.0  0.818797  0.647918
11    160.0  0.817903  0.646695
12    170.0  0.818168  0.645065
13    180.0  0.818548  0.648208
14    190.0  0.817576  0.649705
```

As for the last question, I don't find evidence that explicitly specifying default parameters changes the result, Here's the same as above (note that Tp=0 is the default, changing this will change the models):

```
CCM( dataFrame = sampleData['block_3sp'], E = 3, Tp = 0, knn = 4, tau = -1, 
     columns = "x_t", target = "z_t", libSizes = "50 190 10", sample = 100, 
     exclusionRadius = 2, random = True, replacement = False, seed = 0, 
     includeData = False, verbose = False, showPlot = False )
    LibSize   x_t:z_t   z_t:x_t
0      50.0  0.807819  0.579248
1      60.0  0.809371  0.591536
2      70.0  0.809054  0.600666
3      80.0  0.812662  0.616552
4      90.0  0.814758  0.614433
5     100.0  0.813830  0.628469
6     110.0  0.815882  0.629823
7     120.0  0.817599  0.633728
8     130.0  0.817424  0.643728
9     140.0  0.817365  0.644556
10    150.0  0.817620  0.645696
11    160.0  0.817893  0.645002
12    170.0  0.818888  0.647462
13    180.0  0.818576  0.646756
14    190.0  0.817479  0.648024
```

Results are expressing the same behavior.  Please note `random = True, sample = 100, seed = 0`.  Each model result is the ensemble mean of 100 random libraries. 

If you want to show exactly the same results, you can either use no random libraries and no ensemble means, which is not CCM, or, explicitly set `seed` non-zero, which sets the random number seed.  Default `seed = 0` randomises the seed.

**Comment by pshankinclarke** [comment]
Thank you for your response. I can't seem to find pyEDM 1.7.5.0: 

```
(env) psc@scooter:~$ pip install 'pyEDM == 1.7.5.0'
Collecting pyEDM==1.7.5.0
  Could not find a version that satisfies the requirement pyEDM==1.7.5.0 (from versions: 1.0.1, 1.0.3, 1.0.3.2)
No matching distribution found for pyEDM==1.7.5.0


```

**Comment by SoftwareLiteracy** [comment]
I'm not an expert on pip, but, I can say the latest version is on PyPI: [pyEDM 1.7.5.0](https://pypi.org/project/pyEDM/).  Perhaps this is a pip version issue on your local machine?  In any case, you should be able to uninstall the version you have, then a generic `pip install pyEDM` should work... ?

**Comment by pshankinclarke** [comment]
Yes it was a problem with my local machine. Thank you!

**Comment by pshankinclarke** [comment]
Just to follow-up, switching to the newer version fixed the aforementioned problems. I believe that  the EDM documentation for CCM (https://sugiharalab.github.io/EDM_Documentation/edm_functions/) incorrectly states that the default argument for Tp = 1, not Tp = 0.

**Comment by SoftwareLiteracy** [comment]
Thank you!  Corrected and updated.
